# Generated by Django 3.1.7 on 2021-02-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210223_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('info', models.TextField(blank=True, max_length=250)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='صورة الخدمة '),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, max_length=250, verbose_name='وصف مختصر للخدمة'),
        ),
    ]
