# Generated by Django 3.1.7 on 2021-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210223_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='projects/', verbose_name='الصورة الرئيسة للمشروع')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('service_type', models.CharField(choices=[('الفيلات الخاصة ', 'الفيلات الخاصة '), ('الجامعات والمدارس', 'الجامعات والمدارس'), ('الشركات', 'الشركات'), ('المولات و المحلات ', 'المولات والمحلات')], max_length=50)),
            ],
        ),
    ]
