# Generated by Django 3.1.7 on 2021-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210228_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='info',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
